# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
project = "MATLAB Interface for MLflow"
copyright = "2020-2026, MathWorks, Inc."
author = "MathWorks"

# The short X.Y version
version = ""
# The full version, including alpha/beta/rc tags
release = ""


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
    "sphinx_rtd_theme",
    "sphinx_copybutton",
    "sphinxcontrib.matlab",
    "sphinx.ext.intersphinx",
    "sphinx_new_tab_link",
    "sphinx_multiversion",
]

# copybutton_exclude = '.linenos, .gp, .go'
copybutton_prompt_text = r">> |>>> "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "..."

smv_tag_whitelist = r"^v\d+\.\d+\.\d+$"  # matches v1.0.0, v2.1.3, etc.
smv_branch_whitelist = r"^(main)$"  # include specific branches
smv_remote_whitelist = r"^origin$"  # only use origin remote

intersphinx_mapping = {
    "MLflow": ("https://mlflow.org/docs/latest/api_reference", None),
    "matlab": (
        "https://www.mathworks.com/help/releases/R2025a/matlab",
        "mathworks/matlab.inv",
    ),
    "compiler": (
        "https://www.mathworks.com/help/releases/R2025a/compiler",
        "mathworks/compiler.inv",
    ),
    "compiler_sdk": (
        "https://www.mathworks.com/help/releases/R2025a/compiler_sdk",
        "mathworks/compiler_sdk.inv",
    ),
}

primary_domain = "mat"
add_function_parentheses = False

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = [".rst", ".md"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "README.md"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
## RTD
import sphinx_rtd_theme

html_theme = "sphinx_rtd_theme"
# print(sphinx_rtd_theme.get_html_theme_path())

## Mathworks Customization
html_css_files = [
    "css/mathworks.css",
]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "MATLABInterfaceforMLflow"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    # Fix the tombstone
    "preamble": "\definecolor{VerbatimBorderColor}{rgb}{1,1,1}"
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "MATLABInterfaceforMLflow.tex",
        "MATLAB Interface for MLflow",
        "MathWorks, Inc.",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "MATLABInterfaceforMLflow", "MATLAB Interface for MLflow", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "MATLABInterfaceforMLflow",
        "MATLAB Interface for MLflow",
        author,
        "MATLABInterfaceforMLflow",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

myst_heading_anchors = 5

# enable field lists for nicely documented properties
myst_enable_extensions = ["fieldlist"]
